# create environment:
# conda env create --file conda_env_sat.yml
# -----
# update environment:
# conda env update --file conda_env_sat.yml --prune
# -----
# Insert additional requirements at the bottom.
# -----
name: SAT
channels:
    - conda-forge
    - anaconda
dependencies:
    - python=3.8.1
    - numpy=1.18.1
    - scipy=1.4.1
    - matplotlib=3.1.3
    - pandas=1.0.0
    - xlrd=1.2.0
    - seaborn=0.9.0
    - biopython=1.77
    - ipykernel
    - jupyter=1.0.0
    - jupyterlab=1.2.6
    - mdanalysis=1.0.1
    - mdanalysistests=1.0.1
    - jupyter_contrib_nbextensions=0.5.1
    - rise=5.6.0
    - click
    - sphinx
    - python-dotenv
    - pip
    - nglview
